import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { authenticateRequest, unauthorizedResponse, validateString } from "../_shared/auth.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const COACHING_STEPS = [
  { phase: 'GOAL', stepNum: 1, title: 'The Goal', question: 'What is your goal? Be as specific as you can. What exactly do you want to achieve?' },
  { phase: 'GOAL', stepNum: 2, title: 'The Why', question: 'Why does this matter to you? What will achieving this enable in your life?' },
  { phase: 'GOAL', stepNum: 3, title: 'Excitement Level', question: 'On a scale of 1-10, how excited are you about this goal? If below 8, what would boost your excitement?' },
  { phase: 'PLAN', stepNum: 4, title: 'Major Moves', question: 'What are the 3-5 major milestones or projects you\'ll need to complete to reach this goal?' },
  { phase: 'PLAN', stepNum: 5, title: 'Plan Confidence', question: 'If you followed this plan perfectly, what\'s your confidence level (%) that you\'d achieve your goal? What\'s missing?' },
  { phase: 'PLAN', stepNum: 6, title: 'Reality Check', question: 'Given your real life (work, studies, constraints), what\'s your ACTUAL confidence you\'ll follow through? What needs to change to boost it?' },
  { phase: 'PLAN', stepNum: 7, title: 'Plan Refinement', question: 'Based on that real confidence level, should we adjust your goal, timeline, or plan? What changes would make this more realistic?' },
  { phase: 'SYSTEM', stepNum: 8, title: 'Reminders & Cues', question: 'What physical or digital reminders will you set to keep this goal front-and-center daily? (calendar blocks, sticky notes, wallpapers, etc.)' },
  { phase: 'SYSTEM', stepNum: 9, title: 'Tracking Metrics', question: 'How will you track progress? What metrics matter? How often will you review (weekly, monthly)?' },
  { phase: 'SYSTEM', stepNum: 10, title: 'Potential Blockers', question: 'What are the 3 biggest obstacles that might derail you? (Be honest - identify real risks)' },
  { phase: 'SYSTEM', stepNum: 11, title: 'Accountability', question: 'Who or what will hold you accountable? (friend, mentor, public commitment, daily check-in ritual)' },
  { phase: 'SYSTEM', stepNum: 12, title: 'Next Actions', question: 'What is the ONE thing you\'ll do THIS WEEK to start? (Get specific - not "work on goal", but the actual action)' },
];

const GPS_COACH_SYSTEM_PROMPT = `You are a GPS Life Coach guiding users through Ali Abdaal's goal-setting framework. Your role is to help users create a clear, actionable GPS Blueprint for their goals.

GPS Framework:
- G = GOAL (Steps 1-3): What do you want? Why? How excited are you?
- P = PLAN (Steps 4-7): Major moves, confidence check, reality adjustment, refinement
- S = SYSTEM (Steps 8-12): Reminders, tracking, obstacles, accountability, next actions

Your Coaching Style:
- Be warm, encouraging, and genuinely interested in their success
- Ask ONE question at a time and listen deeply
- Acknowledge their responses with brief, insightful reflections before moving forward
- Push gently when answers are vague - help them get specific
- Be realistic but not discouraging - balance optimism with practicality
- For ADHD-friendly advice, suggest concrete systems over willpower

When generating the FINAL BLUEPRINT (at step 12):
You MUST format the blueprint EXACTLY as follows, with all sections clearly marked:

# GPS Blueprint: [Goal Title]

## 1. The Goal
[Their specific goal statement, refined through coaching]

## 2. The Why
[Their emotional motivation and what achieving this enables]

## 3. Anti-Goals & Constraints
[What they're NOT willing to sacrifice - derived from their answers]

## 4. The Plan
[3-5 Major Moves/Milestones they identified]

## 5. Plan Confidence
- Theory: X% (if they followed perfectly)
- Practice: Y% (given real-life constraints)
- Key gaps to address: [list]

## 6. Potential Obstacles
1. [Obstacle 1]
2. [Obstacle 2]
3. [Obstacle 3]

## 7. The System

### Reminders
[Their physical/digital cues]

### Tracking
[Metrics and review cadence]

### Accountability
[Their accountability structure]

## 8. Next Actions - THIS WEEK
1. [Specific action from step 12]
2. [Any additional immediate actions derived from coaching]

---
*Generated by AURELIA GPS Coach on [current date]*`;

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { user, error: authError } = await authenticateRequest(req);
    if (authError || !user) {
      return unauthorizedResponse(authError || "Unauthorized", corsHeaders);
    }

    const body = await req.json();
    const { message, currentStep, coachingHistory, action } = body;

    // Validate inputs
    const validatedMessage = validateString(message, 5000);
    if (!validatedMessage && action !== 'start' && action !== 'generate_blueprint') {
      return new Response(
        JSON.stringify({ error: "Message is required" }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    // Build conversation messages
    const messages: { role: string; content: string }[] = [];

    // Add coaching history
    if (coachingHistory && Array.isArray(coachingHistory)) {
      for (const entry of coachingHistory) {
        if (entry.question) {
          messages.push({ role: 'assistant', content: entry.question });
        }
        if (entry.answer) {
          messages.push({ role: 'user', content: entry.answer });
        }
        if (entry.aiAck) {
          messages.push({ role: 'assistant', content: entry.aiAck });
        }
      }
    }

    // Add current message if provided
    if (validatedMessage) {
      messages.push({ role: 'user', content: validatedMessage });
    }

    // Determine the prompt based on action/step
    let contextPrompt = '';
    const step = typeof currentStep === 'number' ? currentStep : 0;

    if (action === 'start') {
      contextPrompt = `Begin the GPS coaching session. Introduce yourself briefly and ask the first question about their goal. Keep it warm and inviting.`;
    } else if (action === 'generate_blueprint' || step >= 12) {
      contextPrompt = `The user has completed all 12 steps. Based on their responses throughout the coaching session, generate a complete GPS Blueprint. Make sure to include ALL sections as specified in your instructions. Be comprehensive but concise.`;
    } else {
      const currentStepInfo = COACHING_STEPS[step];
      const nextStepInfo = COACHING_STEPS[step] || null;
      contextPrompt = `You are at Step ${step + 1} of 12.
Current phase: ${currentStepInfo?.phase || 'GOAL'}
Step title: ${currentStepInfo?.title || 'The Goal'}

The user just responded. Acknowledge their response with a brief, insightful reflection (1-2 sentences), then ${step < 11 ? `ask the next question: "${nextStepInfo?.question || ''}"` : 'let them know we\'re about to generate their blueprint and ask if they want to add anything before we do.'}`;
    }

    // Add context to system prompt
    const fullSystemPrompt = `${GPS_COACH_SYSTEM_PROMPT}

CURRENT CONTEXT:
${contextPrompt}`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: fullSystemPrompt },
          ...messages,
        ],
        stream: true,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again in a moment." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "AI credits exhausted. Please add credits to continue." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const errorText = await response.text();
      console.error("AI Gateway error:", response.status, errorText);
      throw new Error(`AI Gateway error: ${response.status}`);
    }

    return new Response(response.body, {
      headers: {
        ...corsHeaders,
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
      },
    });
  } catch (error) {
    console.error("GPS Coach error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
