// Core types for AXIOM + AURELIA system

export type FocusArea = 'study' | 'career' | 'finance' | 'relationships' | 'health';
export type EntityType = 'course' | 'project' | 'client' | 'skill' | 'person' | 'goal' | 'resource';
export type AgentType = 'DEXTER' | 'MENTOR' | 'ARCHITECT' | 'GENERAL';
export type PatternType = 'energy_time' | 'decision_quality' | 'focus_sequence' | 'stress_trigger' | 'success_factor';
export type TaskType = 'learn' | 'build' | 'money';

// Decision context from user input
export interface DecisionContext {
  question: string;
  focusArea: FocusArea;
  energyLevel?: 1 | 2 | 3 | 4 | 5;
  timeAvailable?: string;
  stressLevel?: 1 | 2 | 3 | 4 | 5;
  metadata?: Record<string, any>;
}

// AXIOM recommendation output
export interface Recommendation {
  answer: string;
  confidence: number;
  agent: AgentType;
  reasoning: string;
  citations: Citation[];
  nextSteps?: string[];
}

// RAG citation
export interface Citation {
  source: string;
  title: string;
  excerpt: string;
  similarity: number;
}

// Knowledge entity (from Notion or manual input)
export interface KnowledgeEntity {
  id: string;
  userId: string;
  entityType: EntityType;
  title: string;
  focusArea: FocusArea;
  metadata: Record<string, any>;
  embedding?: number[];
  createdAt: string;
  updatedAt: string;
}

// Decision record
export interface Decision {
  id: string;
  userId: string;
  question: string;
  context: DecisionContext;
  agentUsed: AgentType;
  recommendation: string;
  confidenceScore: number;
  ragCitations: Citation[];
  userFeedback?: 1 | 2 | 3 | 4 | 5;
  userNotes?: string;
  embedding?: number[];
  createdAt: string;
}

// Pattern learned by AURELIA
export interface PatternCache {
  id: string;
  userId: string;
  patternType: PatternType;
  patternData: Record<string, any>;
  confidence: number;
  sampleCount: number;
  lastSeen: string;
  createdAt: string;
}

// Notion chunk for RAG
export interface NotionChunk {
  id: string;
  userId: string;
  pageId: string;
  pageTitle: string;
  chunkText: string;
  chunkIndex: number;
  metadata: Record<string, any>;
  embedding?: number[];
  createdAt: string;
}

// AURELIA 5D health scores
export interface HealthScore {
  id: string;
  userId: string;
  date: string;
  emotionScore: number;
  mindScore: number;
  bodyScore: number;
  soulScore: number;
  hormonesScore: number;
  overallScore: number;
  metadata: Record<string, any>;
  createdAt: string;
}

// Daily task generated by AURELIA
export interface DailyTask {
  id: string;
  userId: string;
  date: string;
  taskType: TaskType;
  title: string;
  description?: string;
  priority: 1 | 2 | 3;
  completed: boolean;
  energyCost: 1 | 2 | 3 | 4 | 5;
  createdAt: string;
}

// User profile
export interface Profile {
  id: string;
  email: string;
  fullName?: string;
  createdAt: string;
  updatedAt: string;
}
